Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/ExtraSpacing:
  Description: 'Do not use unnecessary spacing.'
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/PredicateName:
  NameWhitelist:
    - has_blueprint

Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Enabled: false

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
